const STORAGE_KEY="focusHubData_v1";
const defaults={
 reminders:[
  "By July 2027, physical work is no longer the main source of my income.",
  "Move upstream: inspect, plan, estimate, coordinate, sell, and control quality.",
  "Build capability around real paid work first; add certificates only where they unlock a clear opportunity.",
  "Renoweet is a vehicle. Build systems so the business depends less on my own hands.",
  "Use Renoweet to move upstream: more estimating, planning, coordination and quality control; less dependence on your own physical labour.",
  "Do one action that improves future income, not only today's cash.",
  "Keep what earns, saves, protects, or is used. Sell or remove what only occupies space."
 ],
 links:[
  {name:"CV / Profile",icon:"CV",url:"https://mahmoudalkayri.github.io/Profile/",target:"focus_profile"},
  {name:"Renoweet OS",icon:"OS",url:"./Renoweet-OS-Drive-v2.2.html",target:"focus_os"},
  {name:"Bookkeeping",icon:"€",url:"./Renoweet-Bookkeeping-Drive-v2.2.html",target:"focus_bookkeeping"},
  {name:"Renoweet BOD",icon:"B",url:"./Renoweet-BOD-Drive-v2.2.html",target:"focus_bod"}
 ],
 goals:[
  {id:"g1",title:"Physical work is no longer my primary income source",start:"2026-09-09",target:"2027-07-31",progress:10,note:"Shift toward project coordination, estimating, technical planning, selling, systems and subcontracted execution."},
  {id:"g2",title:"Build Dutch professional construction exposure",start:"2026-09-09",target:"2027-03-31",progress:5,note:"Use targeted bridge opportunities in MEP coordination, work preparation or project controls."},
  {id:"g3",title:"Reduce unnecessary recurring expenses",start:"2026-09-09",target:"2026-10-31",progress:15,note:"Start with storage. Keep only items whose value exceeds the cost and friction of keeping them."}
 ],
 metrics:[
  {id:"m1",name:"Income from non-physical work",value:0,unit:"%",target:60,note:"Planning, coordination, estimating, project controls, management, margin from subcontracted work."},
  {id:"m2",name:"Owner physical labour",value:35,unit:"hrs/week",target:15,note:"Track actual hands-on site hours. Goal is down, without collapsing income."},
  {id:"m3",name:"Renoweet monthly revenue",value:3000,unit:"€/month",target:8000,note:"Use a rolling 3-month average when possible."},
  {id:"m4",name:"Monthly recurring waste removed",value:0,unit:"€/month",target:250,note:"Subscriptions, storage, duplicate services, unused equipment holding costs."},
  {id:"m5",name:"Technical opportunity actions",value:0,unit:"/month",target:6,note:"Targeted contractor outreach, estimating/work-preparation offers, site/project support pitches or qualified sales conversations."},
  {id:"m6",name:"Dutch construction learning",value:2,unit:"hrs/week",target:5,note:"Vocabulary, drawings, standards and real project exposure."}
 ],
 expenses:[
  {id:"e1",name:"Storage box",cost:124,frequency:"monthly",lastUsed:"Mixed — table saw matters; many stored items unused for a long time",income:1,time:1,replace:2,use:1,note:"Dewalt table saw is the key valuable item. The rest needs a keep/sell/dispose inventory."}
 ]
};
let data=loadData(),reminderIndex=0,reminderTimer,deferredPrompt=null,activeEdit=null;
function clone(o){return JSON.parse(JSON.stringify(o))}function loadData(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));return p?{...clone(defaults),...p}:clone(defaults)}catch{return clone(defaults)}}function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll()}function euro(n){return new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(n||0)}function annualCost(c,f){return f==="monthly"?c*12:f==="yearly"?c:c}function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function switchView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active-view",v.id===id));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.view===id));window.scrollTo({top:0,behavior:"smooth"})}document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));document.querySelectorAll("[data-open-view]").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.openView)));
function updateOnline(){const b=document.getElementById("onlineBadge");b.textContent=navigator.onLine?"Online":"Offline";b.style.background=navigator.onLine?"rgba(43,190,125,.22)":"rgba(255,255,255,.12)"}window.addEventListener("online",updateOnline);window.addEventListener("offline",updateOnline);updateOnline();
function renderReminders(){const x=data.reminders;if(!x.length)return;reminderIndex=(reminderIndex+x.length)%x.length;document.getElementById("reminderText").textContent=x[reminderIndex];document.getElementById("reminderDots").innerHTML=x.map((_,i)=>`<span class="dot ${i===reminderIndex?"active":""}"></span>`).join("")}function moveReminder(d){reminderIndex+=d;renderReminders();restartReminderTimer()}function restartReminderTimer(){clearInterval(reminderTimer);reminderTimer=setInterval(()=>moveReminder(1),10000)}document.getElementById("prevReminder").onclick=()=>moveReminder(-1);document.getElementById("nextReminder").onclick=()=>moveReminder(1);let startX=null;const rc=document.getElementById("reminderCard");rc.addEventListener("pointerdown",e=>startX=e.clientX);rc.addEventListener("pointerup",e=>{if(startX===null)return;const dx=e.clientX-startX;startX=null;if(Math.abs(dx)>45)moveReminder(dx<0?1:-1)});
function openSite(l){const external=/^https?:\/\//i.test(l.url);if(external&&!navigator.onLine){alert("You are offline. The Focus Hub still works, but this website needs an internet connection.");return}const w=window.open(l.url,l.target);if(w){try{w.location.href=l.url;w.focus()}catch(e){}}}function renderLinks(){document.getElementById("linkGrid").innerHTML=data.links.map((l,i)=>`<button class="link-tile" data-link="${i}"><span class="link-icon">${esc(l.icon)}</span><span><span class="link-name">${esc(l.name)}</span><span class="link-url">${esc(l.url.replace("https://",""))}</span></span></button>`).join("");document.querySelectorAll("[data-link]").forEach(b=>b.onclick=()=>openSite(data.links[+b.dataset.link]))}
const actions=["Send one targeted message offering technical work preparation, estimating or renovation project support to a contractor.","Review one Renoweet job and identify which part could have been delegated instead of done by you.","Spend 20 minutes on Dutch construction vocabulary from a real drawing, quote, or project document.","Remove one item from storage today: sell it, move it somewhere cheaper, use it, or dispose of it.","Write one reusable Renoweet checklist, quote template, site-survey form, or handover process.","Call one reliable trade contact who could eventually execute work under your coordination.","Update one metric. The purpose is to see reality, not to judge yourself."];function randomAction(){document.getElementById("todayAction").textContent=actions[Math.floor(Math.random()*actions.length)]}document.getElementById("newActionBtn").onclick=randomAction;
function renderHeadline(){const g=data.goals.find(x=>x.id==="g1")||data.goals[0],p=Math.max(0,Math.min(100,Number(g?.progress||0)));document.getElementById("headlineProgress").style.width=p+"%";document.getElementById("headlineProgressLabel").textContent=p+"%"}
function renderGoals(){const el=document.getElementById("goalsList");el.innerHTML=data.goals.map(g=>`<article class="list-card"><div class="list-head"><div><h3>${esc(g.title)}</h3><div class="list-meta">Started ${esc(g.start||"—")} · Target ${esc(g.target||"—")}</div></div><div class="card-actions"><button class="small-btn" data-edit-goal="${g.id}">Edit</button><button class="small-btn delete" data-delete-goal="${g.id}">Delete</button></div></div><p>${esc(g.note||"")}</p><div class="goal-progress-row"><div class="progress-track"><div class="progress-fill" style="width:${Math.max(0,Math.min(100,+g.progress||0))}%"></div></div><strong>${Math.max(0,Math.min(100,+g.progress||0))}%</strong></div></article>`).join("");document.querySelectorAll("[data-edit-goal]").forEach(b=>b.onclick=()=>openGoalDialog(b.dataset.editGoal));document.querySelectorAll("[data-delete-goal]").forEach(b=>b.onclick=()=>{if(confirm("Delete this goal?")){data.goals=data.goals.filter(g=>g.id!==b.dataset.deleteGoal);saveData()}})}
function metricDirection(m){const v=+m.value||0,t=+m.target||0;if(m.name.toLowerCase().includes("physical labour"))return v<=t?"On target":"Reduce";return v>=t?"On target":"Build"}function renderMetrics(){const el=document.getElementById("metricsList");el.innerHTML=data.metrics.map(m=>`<article class="metric-card"><div class="list-head"><h3>${esc(m.name)}</h3><div class="card-actions"><button class="small-btn" data-edit-metric="${m.id}">Edit</button></div></div><div class="metric-value">${esc(m.value)} <small>${esc(m.unit)}</small></div><div class="metric-target">Target: ${esc(m.target)} ${esc(m.unit)} · ${metricDirection(m)}</div><div class="metric-note">${esc(m.note||"")}</div></article>`).join("");document.querySelectorAll("[data-edit-metric]").forEach(b=>b.onclick=()=>openMetricDialog(b.dataset.editMetric))}
function expenseScore(e){const value=(+e.income||0)*2+(+e.time||0)+(+e.replace||0)+(+e.use||0)*2,annual=annualCost(+e.cost||0,e.frequency);let penalty=0;if(annual>=1500)penalty=4;else if(annual>=750)penalty=3;else if(annual>=300)penalty=2;else if(annual>0)penalty=1;const score=value-penalty;if(score>=10)return{label:"KEEP / PROTECT",cls:"score-good",text:"The item appears to create enough operating value to justify its cost. Still compare cheaper ways to get the same result."};if(score>=5)return{label:"REVIEW / REDUCE",cls:"score-review",text:"There may be value here, but the cost or low usage deserves a cheaper alternative, smaller footprint, sharing, renting, or a deadline to prove usefulness."};return{label:"SELL / CANCEL / REMOVE",cls:"score-cut",text:"The current value is weak relative to the cost. Unless there is a specific near-term use, recover cash/space and stop paying to preserve the option."}}
function renderExpenses(){const el=document.getElementById("expensesList");el.innerHTML=data.expenses.map(e=>{const s=expenseScore(e),annual=annualCost(+e.cost||0,e.frequency);return`<article class="list-card"><div class="list-head"><div><h3>${esc(e.name)}</h3><div class="list-meta">${e.frequency==="once"?"One-time":esc(e.frequency)} · <span class="annual-cost">${e.frequency==="once"?"Cost":"Annual cost"} ${euro(annual)}</span></div></div><div class="card-actions"><button class="small-btn" data-edit-expense="${e.id}">Edit</button><button class="small-btn delete" data-delete-expense="${e.id}">Delete</button></div></div><p>${esc(e.note||"")}</p><div class="list-meta">Last-use note: ${esc(e.lastUsed||"—")}</div><div class="expense-score"><span class="score-pill ${s.cls}">${s.label}</span><span class="list-meta">${s.text}</span></div></article>`}).join("");document.querySelectorAll("[data-edit-expense]").forEach(b=>b.onclick=()=>openExpenseDialog(b.dataset.editExpense));document.querySelectorAll("[data-delete-expense]").forEach(b=>b.onclick=()=>{if(confirm("Delete this expense?")){data.expenses=data.expenses.filter(e=>e.id!==b.dataset.deleteExpense);saveData()}})}
const dialog=document.getElementById("editDialog"),fields=document.getElementById("dialogFields"),dtitle=document.getElementById("dialogTitle");function uid(p){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}function openGoalDialog(id=null){const g=id?data.goals.find(x=>x.id===id):{id:uid("g"),title:"",start:new Date().toISOString().slice(0,10),target:"",progress:0,note:""};activeEdit={type:"goal",id:g.id,isNew:!id};dtitle.textContent=id?"Edit goal":"Add goal";fields.innerHTML=`<label>Goal<input name="title" value="${esc(g.title)}"></label><div class="form-grid"><label>Date started<input name="start" type="date" value="${g.start||""}"></label><label>Planned date<input name="target" type="date" value="${g.target||""}"></label></div><label>Progress %<input name="progress" type="number" min="0" max="100" value="${+g.progress||0}"></label><label>Why / next step<textarea name="note" rows="4">${esc(g.note||"")}</textarea></label>`;dialog.showModal()}
function openMetricDialog(id=null){const m=id?data.metrics.find(x=>x.id===id):{id:uid("m"),name:"",value:0,unit:"",target:0,note:""};activeEdit={type:"metric",id:m.id,isNew:!id};dtitle.textContent=id?"Edit metric":"Add metric";fields.innerHTML=`<label>Metric<input name="name" value="${esc(m.name)}"></label><div class="form-grid"><label>Current value<input name="value" type="number" step="0.1" value="${m.value}"></label><label>Unit<input name="unit" value="${esc(m.unit)}" placeholder="%, €/month, hrs/week"></label></div><label>Target<input name="target" type="number" step="0.1" value="${m.target}"></label><label>Meaning / how to measure<textarea name="note" rows="3">${esc(m.note||"")}</textarea></label>`;dialog.showModal()}
function openExpenseDialog(id=null){const e=id?data.expenses.find(x=>x.id===id):{id:uid("e"),name:"",cost:0,frequency:"monthly",lastUsed:"",income:0,time:0,replace:0,use:0,note:""};activeEdit={type:"expense",id:e.id,isNew:!id};dtitle.textContent=id?"Edit expense":"Add expense";fields.innerHTML=`<label>Expense / item<input name="name" value="${esc(e.name)}"></label><div class="form-grid"><label>Cost €<input name="cost" type="number" min="0" step="0.01" value="${e.cost}"></label><label>Frequency<select name="frequency"><option ${e.frequency==="monthly"?"selected":""} value="monthly">Monthly</option><option ${e.frequency==="yearly"?"selected":""} value="yearly">Yearly</option><option ${e.frequency==="once"?"selected":""} value="once">One-time</option></select></label></div><label>Last used / usage note<input name="lastUsed" value="${esc(e.lastUsed||"")}"></label><div class="form-grid"><label>Income value (0–5)<input name="income" type="number" min="0" max="5" value="${e.income}"></label><label>Time saved (0–5)<input name="time" type="number" min="0" max="5" value="${e.time}"></label><label>Replacement difficulty (0–5)<input name="replace" type="number" min="0" max="5" value="${e.replace}"></label><label>Regular use (0–5)<input name="use" type="number" min="0" max="5" value="${e.use}"></label></div><label>Notes<textarea name="note" rows="4">${esc(e.note||"")}</textarea></label>`;dialog.showModal()}
document.getElementById("addGoalBtn").onclick=()=>openGoalDialog();document.getElementById("addMetricBtn").onclick=()=>openMetricDialog();document.getElementById("addExpenseBtn").onclick=()=>openExpenseDialog();document.getElementById("editForm").addEventListener("submit",e=>{if(!activeEdit)return;e.preventDefault();const f=new FormData(e.currentTarget),obj=Object.fromEntries(f.entries());if(activeEdit.type==="goal"){Object.assign(obj,{id:activeEdit.id,progress:+obj.progress||0});data.goals=activeEdit.isNew?[...data.goals,obj]:data.goals.map(x=>x.id===activeEdit.id?obj:x)}else if(activeEdit.type==="metric"){Object.assign(obj,{id:activeEdit.id,value:+obj.value||0,target:+obj.target||0});data.metrics=activeEdit.isNew?[...data.metrics,obj]:data.metrics.map(x=>x.id===activeEdit.id?obj:x)}else{Object.assign(obj,{id:activeEdit.id,cost:+obj.cost||0,income:+obj.income||0,time:+obj.time||0,replace:+obj.replace||0,use:+obj.use||0});data.expenses=activeEdit.isNew?[...data.expenses,obj]:data.expenses.map(x=>x.id===activeEdit.id?obj:x)}activeEdit=null;dialog.close();saveData()});
document.getElementById("evaluateBtn").onclick=()=>{const e={name:document.getElementById("qItem").value||"This item",cost:+document.getElementById("qCost").value||0,frequency:document.getElementById("qFrequency").value,lastUsed:+document.getElementById("qLastUsed").value,income:+document.getElementById("qIncome").value,time:+document.getElementById("qTime").value,replace:+document.getElementById("qReplace").value,use:+document.getElementById("qUse").value};const s=expenseScore(e),annual=annualCost(e.cost,e.frequency),inactivity=e.lastUsed>=5?" Long inactivity is a strong signal that you are paying to preserve an option rather than a working asset.":"";const r=document.getElementById("quickResult");r.classList.remove("hidden");r.innerHTML=`<strong>${esc(e.name)}: ${s.label}</strong><br>${e.frequency==="once"?"Cost":"Annualized cost"}: <strong>${euro(annual)}</strong>.<br>${s.text}${inactivity}`};
document.getElementById("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="renoweet-focus-hub-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)};document.getElementById("importInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{data={...clone(defaults),...JSON.parse(await file.text())};saveData();alert("Backup imported.")}catch{alert("That file could not be imported.")}};document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset all goals, metrics and expenses to the original starter data?")){data=clone(defaults);saveData()}};
function renderAll(){renderReminders();renderLinks();renderHeadline();renderGoals();renderMetrics();renderExpenses()}renderAll();randomAction();restartReminderTimer();if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"))}window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;document.getElementById("installBtn").classList.remove("hidden")});document.getElementById("installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById("installBtn").classList.add("hidden")};
