(function(){
'use strict';
let state={year:RenoweetDrive.currentYear(),activeYear:RenoweetDrive.currentYear(),readOnly:false,baseline:null,sectionRevision:0,connected:false,saving:false,timer:null,selectedQuarter:Math.floor(new Date().getMonth()/3)+1,periods:{}};
const snapshot=()=>({invoices:RenoweetDrive.clone(data.invoices||[]),expenses:RenoweetDrive.clone(data.expenses||[]),fuel:RenoweetDrive.clone(data.fuel||[]),auto:RenoweetDrive.clone(data.auto||[]),deleted:RenoweetDrive.clone(data.deleted||[]),control:RenoweetDrive.clone(data.control||{})});
function status(t){const e=document.getElementById('status');if(e)e.textContent=t}
function periodKey(q=state.selectedQuarter){return `${state.year}-Q${q}`}
function applySelectedPeriod(){currentBookkeepingFileName=`Renoweet-${state.year}-Q${state.selectedQuarter}.json`;const p=state.periods?.[periodKey()]||{};data.control=data.control||{};data.control.BTWStatus=p.btwStatus||'Draft';data.control.BTWFiledDate=p.filedDate||'';data.control.BTWActualAmount=p.actualAmount??'';data.control.BTWNote=p.note||'';data.control.PeriodClosed=p.status==='closed'?'Yes':'No'}
function syncPeriodState(c){state.periods=RenoweetDrive.clone(c.periods||{});applySelectedPeriod()}
function applyRemote(x,rerender=true){data={invoices:RenoweetDrive.clone(x.invoices||[]),expenses:RenoweetDrive.clone(x.expenses||[]),fuel:RenoweetDrive.clone(x.fuel||[]),auto:RenoweetDrive.clone(x.auto||[]),deleted:RenoweetDrive.clone(x.deleted||[]),control:RenoweetDrive.clone(x.control||{})};if(rerender)try{render()}catch(e){};try{scheduleBrowserCache(false)}catch(e){}}
function updateReadOnlyUI(){
 const top=document.querySelector('header .top');let el=document.getElementById('driveHistoricalBannerBK');
 if(state.readOnly){
  if(!el){el=document.createElement('div');el.id='driveHistoricalBannerBK';el.style.cssText='padding:8px 12px;border:1px solid #d6a23d;border-radius:9px;background:rgba(214,162,61,.12);font-weight:700;margin:6px 0';(top?.parentElement||document.body).insertBefore(el,top?.nextSibling||null)}
  el.textContent=`Historical year ${state.year} — READ ONLY. Financial records cannot be changed or saved.`;
 }else if(el)el.remove();
 for(const id of ['saveNowBtn','quarterCloseBtn','quarterReopenBtn','yearArchiveBtn','syncOSBtn']){const b=document.getElementById(id);if(b)b.disabled=!!state.readOnly}
}
async function refreshYearSelector(){
 const info=await RenoweetDrive.listAvailableYears();state.activeYear=Number(info.activeYear||RenoweetDrive.currentYear());
 const sel=document.getElementById('driveYearSelectBK');if(sel){const years=[...new Set([state.year,...info.years])].sort((a,b)=>b-a);sel.innerHTML=years.map(y=>`<option value="${y}" ${y===state.year?'selected':''}>${y}${y===state.activeYear?' — Current':' — Archive'}</option>`).join('')}
 const qsel=document.getElementById('driveQuarterSelect');if(qsel)qsel.innerHTML=[1,2,3,4].map(q=>`<option value="${q}" ${q===state.selectedQuarter?'selected':''}>Q${q} ${state.year}</option>`).join('');
 updateReadOnlyUI();return info;
}
async function selectYear(year){
 year=Number(year);if(!Number.isInteger(year)||year<2000||year>2100||year===state.year)return;
 if(!RenoweetDrive.clientId())RenoweetDrive.configure();if(!RenoweetDrive.clientId())return;
 try{status(`Loading ${year} from Google Drive…`);await RenoweetDrive.authorize(true);const info=await RenoweetDrive.listAvailableYears();const active=Number(info.activeYear||RenoweetDrive.currentYear());const remote=await RenoweetDrive.loadExistingYear(year);if(!remote){alert(`No Renoweet-${year}.json database exists in Google Drive.`);await refreshYearSelector();return}
  state.year=year;state.activeYear=active;state.readOnly=year!==active;syncPeriodState(remote.data);applyRemote(remote.data.bookkeeping);applySelectedPeriod();state.sectionRevision=Number(remote.data.meta.sections.bookkeepingRevision||0);state.baseline=RenoweetDrive.clone(remote.data.bookkeeping);state.connected=true;status(state.readOnly?`Historical ${year} • READ ONLY • bookkeeping revision ${state.sectionRevision} • checksum verified`:`Google Drive connected ✓ • bookkeeping revision ${state.sectionRevision} • checksum verified`);await refreshYearSelector();updateReadOnlyUI();
 }catch(e){console.error(e);alert(e.message);await refreshYearSelector()}
}
async function connectDrive(){try{if(!RenoweetDrive.clientId())RenoweetDrive.configure();if(!RenoweetDrive.clientId())return;status('Connecting Google Drive • validating checksum…');await RenoweetDrive.authorize(true);const info=await RenoweetDrive.listAvailableYears();state.activeYear=Number(info.activeYear||RenoweetDrive.currentYear());if(!info.years.includes(state.year))state.year=state.activeYear;state.readOnly=state.year!==state.activeYear;const remote=state.readOnly?await RenoweetDrive.loadExistingYear(state.year):await RenoweetDrive.loadYear(state.year,true);window.__renoweetCanonical=RenoweetDrive.clone(remote?.data||{});if(!remote)throw new Error(`Renoweet-${state.year}.json was not found.`);syncPeriodState(remote.data);const r=remote.data.bookkeeping,hasRemote=(r.invoices?.length||r.expenses?.length||r.fuel?.length||r.auto?.length||r.deleted?.length),local=snapshot(),hasLocal=(local.invoices.length||local.expenses.length||local.fuel.length||local.auto.length||local.deleted.length);if(!state.readOnly&&!hasRemote&&hasLocal&&confirm(`Renoweet-${state.year}.json has no bookkeeping records yet. Upload the bookkeeping currently shown on this device?`)){const saved=await RenoweetDrive.saveSection('bookkeeping',local,{year:state.year,sectionRevision:0,forceRecovery:true,recoveryReason:'initial-bookkeeping-import'});applyRemote(saved.data.bookkeeping,false);state.sectionRevision=saved.sectionRevision}else{applyRemote(r);state.sectionRevision=remote.data.meta.sections.bookkeepingRevision}state.baseline=RenoweetDrive.clone(data);state.connected=true;status(state.readOnly?`Historical ${state.year} • READ ONLY • bookkeeping revision ${state.sectionRevision} • checksum verified`:`Google Drive connected ✓ • bookkeeping revision ${state.sectionRevision} • checksum verified`);await refreshYearSelector();updateReadOnlyUI();await updateOSPendingButton(remote.data);const b=document.getElementById('saveNowBtn');if(b)b.disabled=state.readOnly}catch(e){console.error(e);status('Drive not connected');alert(e.message)}}
async function saveDrive(manual=false){if(state.readOnly){if(manual)alert(`Renoweet ${state.year} is a historical read-only year. Switch back to ${state.activeYear} to save financial changes.`);return false}if(state.saving)return false;if(!state.connected){if(manual)await connectDrive();else return false;if(!state.connected)return false}state.saving=true;clearTimeout(state.timer);try{try{scheduleBrowserCache(true)}catch(e){};status('Saving bookkeeping • checking closed periods and Drive revision…');const saved=await RenoweetDrive.saveSection('bookkeeping',snapshot(),{...state,forceRecovery:manual,recoveryReason:manual?'manual-bookkeeping-save':'bookkeeping-autosave'});applyRemote(saved.data.bookkeeping,false);state.sectionRevision=saved.sectionRevision;window.__renoweetCanonical=RenoweetDrive.clone(saved.data||window.__renoweetCanonical||{});state.baseline=RenoweetDrive.clone(saved.data.bookkeeping);try{scheduleBrowserCache(false)}catch(e){};status(`Saved & verified ✓ • bookkeeping revision ${state.sectionRevision}`);return true}catch(e){console.error(e);if(e.name==='RenoweetConflictError'){status('Newer bookkeeping exists on another device • refresh before saving');if(manual)alert('Bookkeeping changed on another device. Renoweet stopped the save rather than guessing with financial records.\n\nRefresh, review the newer data, then save again.')}else if(e.name==='RenoweetClosedPeriodError'){status('Save blocked • closed BTW quarter');alert(e.message)}else{status('Save stopped');if(manual)alert(e.message)}return false}finally{state.saving=false}}
function scheduleDrive(){if(state.readOnly){updateReadOnlyUI();return}try{scheduleBrowserCache(true)}catch(e){};clearTimeout(state.timer);state.timer=setTimeout(()=>saveDrive(false),900)}
async function refreshDrive(){try{
 if(!RenoweetDrive.clientId())RenoweetDrive.configure();if(!RenoweetDrive.clientId())return;
 status('Refreshing Google Drive…');
 // A separate browser tab has separate session storage. Refresh must therefore be able to authorize itself.
 await RenoweetDrive.authorize(true);
 const r=state.readOnly?await RenoweetDrive.loadExistingYear(state.year):await RenoweetDrive.loadYear(state.year,true);window.__renoweetCanonical=RenoweetDrive.clone(r?.data||{});if(!r)throw new Error(`Renoweet-${state.year}.json was not found.`);
 syncPeriodState(r.data);applyRemote(r.data.bookkeeping);applySelectedPeriod();state.sectionRevision=r.data.meta.sections.bookkeepingRevision;state.baseline=RenoweetDrive.clone(r.data.bookkeeping);state.connected=true;
 status(state.readOnly?`Historical ${state.year} • READ ONLY • bookkeeping revision ${state.sectionRevision} • checksum verified`:`Refreshed from Drive ✓ • bookkeeping revision ${state.sectionRevision} • checksum verified`);updateReadOnlyUI();await updateOSPendingButton(r.data)
 }catch(e){console.error(e);status('Drive refresh stopped');alert(e.message)}}

function osInvoiceNo(row){return String(row?.['Invoice number']||row?.['Invoice #']||row?.invoiceNumber||'').trim()}
function bkInvoiceNo(row){return String(row?.['Invoice #']||row?.['Invoice number']||row?.invoiceNumber||'').trim()}
function queuedRowsFromProjects(canonical){
 const out=[];
 for(const p of (canonical?.os?.projects||[])){
  const inv=p?.invoice||{},queued=String(inv.bookkeepingQueuedAt||'').trim(),no=String(inv.number||'').trim();
  if(!queued||!no)continue;
  const est=Array.isArray(p.estimate)?p.estimate:[];
  const subtotal=est.reduce((sum,x)=>sum+(Number(x.qty)||0)*(Number(x.rate)||0),0);
  const vatRate=Number(p?.quote?.vat ?? 21)||0,vat=subtotal*vatRate/100,total=subtotal+vat;
  let due='';try{const d=new Date(String(inv.date||'')+'T12:00:00');if(!isNaN(d)){d.setDate(d.getDate()+(Number(inv.dueDays)||3));due=d.toISOString().slice(0,10)}}catch(e){}
  out.push({'Invoice number':no,'Invoice date':inv.date||'','Due date':due,'Customer':p?.customer?.name||'','Phone':p?.customer?.phone||'','Email':p?.customer?.email||'','Address':p?.customer?.address||'','Project':p?.title||'','Project ID':p?.id||'','Project stage':p?.stage||'','Project created':p?.created||'','Project updated':p?.updated||'','Project address':p?.customer?.address||'','Project description':p?.description||'','Description':est.map(x=>x?.desc||'').filter(Boolean).join(' | '),'Subtotal ex VAT':+subtotal.toFixed(2),'VAT rate':vatRate,'VAT':+vat.toFixed(2),'Total incl VAT':+total.toFixed(2),'Status':'Ready for bookkeeping','Sent at':queued,'Queue token':queued,'Source database':`Renoweet-${state.year}.json`});
 }
 return out;
}
function allOSQueueRows(canonical){
 const map=new Map();
 for(const r of (Array.isArray(canonical?.os?.bookkeeping)?canonical.os.bookkeeping:[])){const no=osInvoiceNo(r);if(no)map.set(no,r)}
 // Project-level queue marker is the durable fallback if the queue-row write was ever missed by an older build.
 for(const r of queuedRowsFromProjects(canonical)){const no=osInvoiceNo(r);if(no&&!map.has(no))map.set(no,r)}
 return [...map.values()];
}
function osPendingRows(canonical){
 const rows=allOSQueueRows(canonical);
 return rows.filter(r=>{
   const no=osInvoiceNo(r); if(!no)return false;
   const existing=(data.invoices||[]).find(x=>bkInvoiceNo(x)===no);
   if(!existing)return true;
   const sent=String(r['Sent at']||'');
   const applied=String(existing['OS sent at']||'');
   return !!sent && sent!==applied;
 });
}
async function updateOSPendingButton(canonical=null){
 try{
   let c=canonical;
   if(!c && state.connected){const r=state.readOnly?await RenoweetDrive.loadExistingYear(state.year):await RenoweetDrive.loadYear(state.year,true);c=r?.data}
   const n=c?osPendingRows(c).length:0;
   const b=document.getElementById('syncOSBtn');
   if(b){b.textContent=n===1?'1 OS invoice waiting to import':`${n} OS invoices waiting to import`;b.title=n?`Import ${n} invoice${n===1?'':'s'} sent from Renoweet OS`:'No OS invoices are waiting';}
   const e=document.getElementById('osSyncStatus');
   if(e)e.innerHTML=`<b>Renoweet OS:</b> ${n} invoice${n===1?'':'s'} waiting to import from projects${state.connected?' • Drive checked':''}.`;
   return n;
 }catch(e){console.warn('Could not update OS invoice queue',e);return 0}
}

async function syncOSFromSameDatabase(){if(state.readOnly){alert(`Historical year ${state.year} is read-only.`);return}try{if(!state.connected)await connectDrive();if(!state.connected)return;const r=await RenoweetDrive.loadYear(state.year,true),pending=osPendingRows(r.data);if(!pending.length){await updateOSPendingButton(r.data);alert('No OS invoices are waiting to import.');return}let added=0,updated=0;for(const osRow of pending){const no=osInvoiceNo(osRow);if(!no)continue;const row=typeof osInvoiceToBookkeeping==='function'?osInvoiceToBookkeeping(osRow):RenoweetDrive.clone(osRow);row['Project']=osRow['Project']||row['Project']||'';row['Project ID']=osRow['Project ID']||row['Project ID']||'';row['Project stage']=osRow['Project stage']||'';row['Project address']=osRow['Project address']||osRow['Address']||'';row['Project description']=osRow['Project description']||'';row['OS sent at']=osRow['Sent at']||'';let i=(data.invoices||[]).findIndex(x=>bkInvoiceNo(x)===no);if(i>=0){data.invoices[i]={...data.invoices[i],...row};updated++}else{data.invoices.push(row);added++}}render();const ok=await saveDrive(true);if(!ok)throw new Error('The invoices were prepared locally but the verified Drive save did not complete.');const latest=await RenoweetDrive.loadYear(state.year,true);await updateOSPendingButton(latest.data);alert(`OS invoice import complete.\n\nNew invoices: ${added}\nUpdated invoices: ${updated}\n\nProject/customer details were copied with each invoice.`)}catch(e){alert(e.message)}}
async function exportJson(){const r=state.connected?(state.readOnly?await RenoweetDrive.loadExistingYear(state.year):await RenoweetDrive.loadYear(state.year,true)):null,c=r?.data||RenoweetDrive.blankCanonical(state.year);c.bookkeeping=snapshot();await RenoweetDrive.downloadJSON(c,`Renoweet-${state.year}-CURRENT.json`)}
async function exportXlsx(){const r=state.connected?(state.readOnly?await RenoweetDrive.loadExistingYear(state.year):await RenoweetDrive.loadYear(state.year,true)):null,c=r?.data||RenoweetDrive.blankCanonical(state.year);c.bookkeeping=snapshot();await RenoweetDrive.downloadXLSX(c,`Renoweet-${state.year}-CURRENT.xlsx`)}
async function completeBackup(){try{if(state.connected&&!state.readOnly&&!(await saveDrive(true)))return;await RenoweetDrive.downloadCompleteBackup(state.year)}catch(e){alert(e.message)}}
async function closeQuarter(q=state.selectedQuarter){if(state.readOnly){alert(`Historical year ${state.year} is read-only.`);return}if(!state.connected)await connectDrive();if(!state.connected)return;q=Number(q);if(![1,2,3,4].includes(q))return;const live0=await RenoweetDrive.loadYear(state.year,true),key=`${state.year}-Q${q}`;syncPeriodState(live0.data);if(live0.data.periods?.[key]?.status==='closed'){alert(`${key} is already closed.`);return}if(!confirm(`Close ${key}?\n\nRenoweet will save and verify bookkeeping, create a permanent XLSX archive, record its checksum in the manifest, and then block later financial edits in this quarter.`))return;if(!(await saveDrive(true)))return;const live=await RenoweetDrive.loadYear(state.year,true),archive=await RenoweetDrive.createArchiveOnDrive(live.data,`Renoweet-${state.year}-Q${q}.xlsx`),closed=await RenoweetDrive.markQuarterClosed(state.year,q,archive);syncPeriodState(closed);render();alert(`${key} is closed.\n\nArchive: ${archive.name}\nThe live database now protects financial records in this quarter from editing.`)}
async function reopenQuarter(q=state.selectedQuarter){if(state.readOnly){alert(`Historical year ${state.year} is read-only.`);return}if(!state.connected)await connectDrive();if(!state.connected)return;q=Number(q);if(![1,2,3,4].includes(q))return;const live=await RenoweetDrive.loadYear(state.year,true);syncPeriodState(live.data);if(live.data.periods?.[`${state.year}-Q${q}`]?.status!=='closed'){alert(`${state.year}-Q${q} is already open.`);return}const reason=prompt('Reason for reopening this closed BTW quarter:','Correction after review');if(reason===null||!reason.trim())return;if(!confirm(`Reopen ${state.year}-Q${q}?\n\nThis action is written to the audit trail. The old archive remains unchanged.`))return;const opened=await RenoweetDrive.reopenQuarter(state.year,q,reason.trim());syncPeriodState(opened);render();alert(`${state.year}-Q${q} reopened. The previous archive remains read-only; create a new close archive after corrections.`)}
async function yearEndArchive(){if(state.readOnly){alert(`Historical year ${state.year} is read-only.`);return}if(!state.connected)await connectDrive();if(!state.connected)return;if(!confirm(`Create the comprehensive ${state.year} FINAL archive now?\n\nThis creates reconstructable XLSX + exact JSON, updates the manifest, and keeps the live database.`))return;if(!(await saveDrive(true)))return;const a=await RenoweetDrive.createFinalArchives(state.year);alert(`Final ${state.year} archives created in Google Drive.\n\n${a.xlsx.name}\n${a.json.name}`)}
async function saveBTWControlDrive(){if(state.readOnly){alert(`Historical year ${state.year} is read-only.`);return}if(!state.connected)await connectDrive();if(!state.connected)return;const patch={btwStatus:document.getElementById('btwFilingStatus')?.value||'Draft',filedDate:document.getElementById('btwFiledDate')?.value||'',actualAmount:document.getElementById('btwActualAmount')?.value||'',note:document.getElementById('btwFilingNote')?.value||''};const c=await RenoweetDrive.updatePeriodInfo(state.year,state.selectedQuarter,patch);syncPeriodState(c);render();alert(`${periodKey()} filing status saved in the yearly database.`)}
function selectQuarter(q){q=Number(q);if(![1,2,3,4].includes(q))return;state.selectedQuarter=q;applySelectedPeriod();render();status(`Viewing Q${q} • Drive ${state.connected?'connected':'not connected'}`)}
try{periodIsClosed=function(){return state.periods?.[periodKey()]?.status==='closed'};vatFilingStatus=function(){return state.periods?.[periodKey()]?.btwStatus||'Draft'};saveBTWControl=saveBTWControlDrive;togglePeriodClosed=async function(){return periodIsClosed()?reopenQuarter(state.selectedQuarter):closeQuarter(state.selectedQuarter)}}catch(e){}
function settings(){const id=RenoweetDrive.configure();if(id)alert('Google Client ID saved on this device. Click Connect Google Drive to authorize.')}
connectWorkbook=connectDrive;saveWorkbook=saveDrive;persist=function(){if(state.readOnly){if(state.baseline)applyRemote(state.baseline);applySelectedPeriod();status(`Historical ${state.year} • READ ONLY • changes were discarded`);updateReadOnlyUI();return}render();scheduleDrive()};scheduleAutoSave=scheduleDrive;syncRenoweetOS=syncOSFromSameDatabase;
window.renoweetDriveBK={connect:connectDrive,save:saveDrive,refresh:refreshDrive,syncOS:syncOSFromSameDatabase,exportJSON:exportJson,exportXLSX:exportXlsx,completeBackup,closeQuarter,reopenQuarter,yearEndArchive,selectQuarter,selectYear,settings,state};
setTimeout(async()=>{const c=document.getElementById('connectBtn'),sy=document.getElementById('syncOSBtn'),ch=document.getElementById('changeOSBtn'),s=document.getElementById('saveNowBtn');if(c){c.textContent='Connect Google Drive';c.onclick=connectDrive}if(sy){sy.textContent='0 OS invoices waiting to import';sy.onclick=syncOSFromSameDatabase}if(ch){ch.textContent='Refresh Drive';ch.onclick=refreshDrive}if(s){s.disabled=false;s.onclick=()=>saveDrive(true)}const top=document.querySelector('header .top');if(top&&!document.getElementById('driveYearSelectBK')){const ysel=document.createElement('select');ysel.id='driveYearSelectBK';ysel.className='secondary';ysel.innerHTML=`<option value="${state.year}">${state.year} — Current</option>`;ysel.onchange=()=>selectYear(ysel.value);top.insertBefore(ysel,document.getElementById('lockBtn'))}if(top&&!document.getElementById('driveQuarterSelect')){const qsel=document.createElement('select');qsel.id='driveQuarterSelect';qsel.className='secondary';qsel.innerHTML=[1,2,3,4].map(q=>`<option value="${q}" ${q===state.selectedQuarter?'selected':''}>Q${q} ${state.year}</option>`).join('');qsel.onchange=()=>selectQuarter(qsel.value);top.insertBefore(qsel,document.getElementById('lockBtn'))}if(top&&!document.getElementById('quarterCloseBtn')){for(const spec of [['quarterCloseBtn','Close BTW quarter',closeQuarter],['quarterReopenBtn','Reopen quarter',reopenQuarter],['completeBackupBtn','Complete backup',completeBackup],['yearArchiveBtn','Year archive',yearEndArchive]]){const b=document.createElement('button');b.id=spec[0];b.className='secondary';b.textContent=spec[1];b.onclick=spec[2];top.insertBefore(b,document.getElementById('lockBtn'))}}applySelectedPeriod();status(`Drive v3 ready • year ${state.year} • Q${state.selectedQuarter} selected • historical years open read-only`);const os=document.getElementById('osSyncStatus');if(os)os.innerHTML='<b>Renoweet OS:</b> connect Drive to check invoices waiting to import.';updateReadOnlyUI();if(state.connected)await updateOSPendingButton()},350);
})();
