/* Renoweet Drive Core v2.0
   Owner-controlled yearly JSON storage for Renoweet OS, Bookkeeping and BOD.
   Safety additions: schema validation, integrity checksum, stable IDs, audit log,
   closed-period protection, recovery snapshots, manifest, reconstructable XLSX,
   and one-click offline ZIP backup.
*/
(function(){
'use strict';
const Core={};
const SCHEMA_VERSION=2, APP_VERSION='drive-v2.5';
const DEFAULT_GOOGLE_CLIENT_ID='819845217406-569349vod25m15sb2omm03do2h1ll976.apps.googleusercontent.com';
const LS={clientId:'renoweet_google_client_id_v1',token:'renoweet_google_access_token_v1',tokenAt:'renoweet_google_token_at_v1',folderId:'renoweet_drive_folder_id_v1',activeFolderId:'renoweet_drive_active_folder_id_v26',archivesFolderId:'renoweet_drive_archives_folder_id_v26',recoveryFolderId:'renoweet_drive_recovery_folder_id_v26',manifestId:'renoweet_drive_manifest_id_v26',activeId:'renoweet_drive_active_id_v1',activeYearId:'renoweet_drive_active_year_id_v25_',year:'renoweet_drive_year_v1',deviceId:'renoweet_device_id_v2',lastRecovery:'renoweet_last_recovery_v2_'};
const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.file';
const ROOT_FOLDER='Renoweet Data', ACTIVE_FOLDER='Active', ARCHIVE_FOLDER='Archives', RECOVERY_FOLDER='Recovery', MANIFEST_NAME='Renoweet-manifest.json';
const CACHE_DB='RenoweetDriveCacheV2', CACHE_STORE='snapshots', RECOVERY_KEEP=20, RECOVERY_INTERVAL_MS=15*60*1000;
let tokenClient=null;
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString();
const currentYear=()=>new Date().getFullYear();
const safeYear=y=>{const n=Number(y);return Number.isInteger(n)&&n>=2020&&n<=2100?n:currentYear()};
const escQ=s=>String(s).replace(/'/g,"\\'");
function randId(prefix='rec'){const u=(crypto.randomUUID?crypto.randomUUID():`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`);return `${prefix}_${u.replace(/-/g,'')}`}
function deviceId(){let id=localStorage.getItem(LS.deviceId);if(!id){id='dev_'+randId('').replace(/^_/,'').slice(0,20);localStorage.setItem(LS.deviceId,id)}return id}
function blankPeriods(year){return Object.fromEntries([1,2,3,4].map(q=>[`${year}-Q${q}`,{status:'open',closedAt:null,archiveFileId:null,archiveChecksum:null,closedRevision:null}]))}
function blankCanonical(year=currentYear()){
 year=safeYear(year);const x={schema:'renoweet.year',schemaVersion:SCHEMA_VERSION,meta:{year,createdAt:now(),updatedAt:now(),revision:0,status:'active',appVersion:APP_VERSION,lastUpdatedBy:deviceId(),sections:{osRevision:0,bookkeepingRevision:0}},periods:blankPeriods(year),integrity:{algorithm:'SHA-256',checksum:'',recordCount:0},os:{projects:[],bookkeeping:[],deleted:[]},bookkeeping:{invoices:[],expenses:[],fuel:[],auto:[],deleted:[],control:{}},audit:[]};return x
}
function quarterFromDate(v){if(v==null||v==='')return null;let d;if(v instanceof Date)d=v;else if(typeof v==='number'&&window.XLSX?.SSF){const z=XLSX.SSF.parse_date_code(v);if(z)d=new Date(z.y,z.m-1,z.d)}if(!d){const s=String(v).trim();const m=s.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})/);if(m)d=new Date(+m[1],+m[2]-1,+m[3]);else{const dm=s.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})/);if(dm)d=new Date(+dm[3],+dm[2]-1,+dm[1]);else d=new Date(s)}}if(!d||isNaN(d))return null;return {year:d.getFullYear(),quarter:Math.floor(d.getMonth()/3)+1}}
function recordDate(r){if(!r||typeof r!=='object')return null;for(const k of ['Date','date','Invoice date','Invoice Date','invoiceDate','Expense date','Expense Date','Payment date','Order Date','Created','created'])if(r[k]){const q=quarterFromDate(r[k]);if(q)return q}return null}
function businessKey(r,type='rec'){
 if(!r||typeof r!=='object')return '';
 const clean=v=>String(v??'').trim().toLowerCase();
 if(type==='invoice')return ['Invoice number','Invoice #','Invoice Number','Date','Invoice date','Customer'].map(k=>clean(r[k])).join('|');
 if(type==='expense'||type==='fuel'||type==='auto')return [clean(r.Date||r.date),clean(r.Supplier),clean(r.Description),clean(r.Gross),clean(r.VAT)].join('|');
 return clean(r.id||r['ID']||r['Line ID']||r['Payment ID']||r['Order ID']||r['Follow-up ID']||r['Activity ID'])||JSON.stringify(r);
}
function inheritIds(payload,remote,type,prefix){const byKey=new Map();(remote||[]).forEach(r=>{if(r?._rid)byKey.set(businessKey(r,type),r._rid)});(payload||[]).forEach(r=>{if(!r._rid){const k=businessKey(r,type);if(k&&byKey.has(k))r._rid=byKey.get(k);else r._rid=randId(prefix)}})}
function ensureProjectIds(projects){const customerMap=new Map();for(const p of projects||[]){if(!p.id)p.id=randId('prj');p.customer=p.customer||{};let ck=[p.customer.email,p.customer.phone,p.customer.name,p.customer.address].map(v=>String(v||'').trim().toLowerCase()).join('|');if(p.customer.id){if(ck)customerMap.set(ck,p.customer.id)}else if(ck&&customerMap.has(ck))p.customer.id=customerMap.get(ck);else{p.customer.id=randId('cus');if(ck)customerMap.set(ck,p.customer.id)};for(const [k,prefix] of [['estimate','est'],['materials','mat'],['documents','doc'],['payments','pay'],['purchaseOrders','po'],['activity','act'],['followUps','fu'],['checklist','chk']])for(const r of (Array.isArray(p[k])?p[k]:[])){if(!r.id)r.id=randId(prefix)}}}
function ensureCanonicalIds(x,remote=null){ensureProjectIds(x.os.projects);if(remote)inheritIds(x.os.bookkeeping,remote.os?.bookkeeping,'invoice','osi');else inheritIds(x.os.bookkeeping,[],'invoice','osi');for(const [k,type,prefix] of [['invoices','invoice','inv'],['expenses','expense','exp'],['fuel','fuel','fuel'],['auto','auto','auto'],['deleted','rec','del']])inheritIds(x.bookkeeping[k],remote?.bookkeeping?.[k]||[],type,prefix);for(const r of x.os.deleted||[])if(!r._rid)r._rid=randId('del');for(const a of x.audit||[])if(!a.eventId)a.eventId=randId('aud');return x}
function normalizeCanonical(v,year=currentYear()){
 const x=(v&&typeof v==='object')?clone(v):blankCanonical(year);x.schema='renoweet.year';x.schemaVersion=Number(x.schemaVersion)||1;x.meta=x.meta||{};x.meta.year=safeYear(x.meta.year||year);x.meta.createdAt=x.meta.createdAt||now();x.meta.updatedAt=x.meta.updatedAt||now();x.meta.revision=Number(x.meta.revision)||0;x.meta.status=x.meta.status||'active';x.meta.appVersion=x.meta.appVersion||APP_VERSION;x.meta.lastUpdatedBy=x.meta.lastUpdatedBy||'';x.meta.sections=x.meta.sections||{};x.meta.sections.osRevision=Number(x.meta.sections.osRevision)||0;x.meta.sections.bookkeepingRevision=Number(x.meta.sections.bookkeepingRevision)||0;
 x.periods=x.periods&&typeof x.periods==='object'?x.periods:blankPeriods(x.meta.year);for(const [k,vv] of Object.entries(blankPeriods(x.meta.year)))x.periods[k]=x.periods[k]||vv;
 x.integrity=x.integrity&&typeof x.integrity==='object'?x.integrity:{algorithm:'SHA-256',checksum:'',recordCount:0};x.integrity.algorithm='SHA-256';x.integrity.checksum=String(x.integrity.checksum||'');x.integrity.recordCount=Number(x.integrity.recordCount)||0;
 x.os=x.os||{};x.os.projects=Array.isArray(x.os.projects)?x.os.projects:[];x.os.bookkeeping=Array.isArray(x.os.bookkeeping)?x.os.bookkeeping:[];x.os.deleted=Array.isArray(x.os.deleted)?x.os.deleted:[];
 x.bookkeeping=x.bookkeeping||{};for(const k of ['invoices','expenses','fuel','auto','deleted'])x.bookkeeping[k]=Array.isArray(x.bookkeeping[k])?x.bookkeeping[k]:[];x.bookkeeping.control=x.bookkeeping.control&&typeof x.bookkeeping.control==='object'?x.bookkeeping.control:{};x.audit=Array.isArray(x.audit)?x.audit:[];ensureCanonicalIds(x);return x
}
function countRecords(x){let n=(x.os.projects||[]).length+(x.os.bookkeeping||[]).length+(x.os.deleted||[]).length;for(const p of x.os.projects||[])for(const k of ['estimate','materials','documents','payments','purchaseOrders','activity','followUps','checklist'])n+=(p[k]||[]).length;for(const k of ['invoices','expenses','fuel','auto','deleted'])n+=(x.bookkeeping[k]||[]).length;return n}
async function sha256Text(text){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function computeChecksum(x){const c=clone(x);c.integrity=c.integrity||{};c.integrity.checksum='';return sha256Text(JSON.stringify(c))}
async function sealCanonical(v){const x=normalizeCanonical(v);x.schemaVersion=SCHEMA_VERSION;x.meta.appVersion=APP_VERSION;x.integrity.recordCount=countRecords(x);x.integrity.checksum=await computeChecksum(x);return x}
async function verifyCanonical(v){const x=normalizeCanonical(v);if(x.schema!=='renoweet.year')throw new Error('Not a Renoweet yearly database.');if(!x.meta||!x.os||!x.bookkeeping||!x.periods)throw new Error('Renoweet database is missing required sections.');if(x.integrity?.checksum){const actual=await computeChecksum(x);if(actual!==x.integrity.checksum){const e=new Error('Renoweet database checksum does not match. Nothing was loaded or overwritten. Use Recovery or a local backup.');e.name='RenoweetIntegrityError';throw e}}return x}
function cacheDB(){return new Promise((resolve,reject)=>{const q=indexedDB.open(CACHE_DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(CACHE_STORE))q.result.createObjectStore(CACHE_STORE)};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function cachePut(key,value){try{const db=await cacheDB();await new Promise((resolve,reject)=>{const tx=db.transaction(CACHE_STORE,'readwrite');tx.objectStore(CACHE_STORE).put({savedAt:now(),value},key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch(e){console.warn('Renoweet local safety cache failed',e)}}
async function cacheGet(key){try{const db=await cacheDB();return await new Promise((resolve,reject)=>{const q=db.transaction(CACHE_STORE).objectStore(CACHE_STORE).get(key);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)})}catch(e){return null}}
function clientId(){return localStorage.getItem(LS.clientId)||DEFAULT_GOOGLE_CLIENT_ID}function setClientId(id){id=String(id||'').trim();if(id)localStorage.setItem(LS.clientId,id);else localStorage.removeItem(LS.clientId);tokenClient=null;return id}function accessToken(){return sessionStorage.getItem(LS.token)||''}function setToken(t){if(t){sessionStorage.setItem(LS.token,t);sessionStorage.setItem(LS.tokenAt,String(Date.now()))}else{sessionStorage.removeItem(LS.token);sessionStorage.removeItem(LS.tokenAt)}}
function gisReady(){return !!(window.google&&google.accounts&&google.accounts.oauth2)}
function initTokenClient(){if(tokenClient)return tokenClient;if(!gisReady())throw new Error('Google authorization library is still loading.');const id=clientId();if(!id)throw new Error('Google OAuth Client ID is not configured.');tokenClient=google.accounts.oauth2.initTokenClient({client_id:id,scope:DRIVE_SCOPE,callback:()=>{}});return tokenClient}
function authorize(interactive=true){return new Promise((resolve,reject)=>{try{const tc=initTokenClient();tc.callback=r=>{if(r&&r.access_token){setToken(r.access_token);resolve(r.access_token)}else reject(new Error(r?.error_description||r?.error||'Google authorization failed.'))};tc.requestAccessToken({prompt:accessToken()?'':(interactive?'consent':'')})}catch(e){reject(e)}})}async function token(){return accessToken()||await authorize(true)}
async function driveFetch(url,opt={}){let t=await token();const headers=new Headers(opt.headers||{});headers.set('Authorization','Bearer '+t);let r=await fetch(url,{...opt,headers});if(r.status===401){setToken('');t=await authorize(true);headers.set('Authorization','Bearer '+t);r=await fetch(url,{...opt,headers})}if(!r.ok){let text=await r.text();throw new Error(`Google Drive ${r.status}: ${text.slice(0,500)}`)}return r}
async function listFiles(q,fields='files(id,name,mimeType,modifiedTime,version,md5Checksum,parents)'){const u='https://www.googleapis.com/drive/v3/files?spaces=drive&pageSize=100&fields='+encodeURIComponent(fields)+'&q='+encodeURIComponent(q);return (await (await driveFetch(u)).json()).files||[]}
async function createMetadata(meta){const r=await driveFetch('https://www.googleapis.com/drive/v3/files?fields=id,name,mimeType,modifiedTime,version,parents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(meta)});return r.json()}
async function createTextFile(name,parentId,text,mime='application/json'){const boundary='renoweet_'+Math.random().toString(36).slice(2),body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n`,JSON.stringify({name,mimeType:mime,parents:parentId?[parentId]:undefined}),`\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`,text,`\r\n--${boundary}--`]);const r=await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime,version,md5Checksum,parents',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});return r.json()}
async function createBinaryFile(name,parentId,bytes,mime){const boundary='renoweet_'+Math.random().toString(36).slice(2),blob=new Blob([bytes],{type:mime}),body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n`,JSON.stringify({name,mimeType:mime,parents:parentId?[parentId]:undefined}),`\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`,blob,`\r\n--${boundary}--`]);const r=await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime,version,md5Checksum,parents',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});return r.json()}
async function updateTextFile(id,text,mime='application/json'){const r=await driveFetch(`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(id)}?uploadType=media&fields=id,name,modifiedTime,version,md5Checksum,parents`,{method:'PATCH',headers:{'Content-Type':mime},body:text});return r.json()}
async function getMeta(id){return (await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name,mimeType,modifiedTime,version,md5Checksum,parents`)).json()}async function getText(id){return (await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`)).text()}async function getBytes(id){return (await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`)).arrayBuffer()}
async function usableMeta(id,expectedName=null,expectedMime=null){if(!id)return null;try{const m=await getMeta(id);if(!m?.id)return null;if(expectedName&&m.name!==expectedName)return null;if(expectedMime&&m.mimeType!==expectedMime)return null;return m}catch(e){return null}}
async function ensureFolder(name,parentId=null,cacheKey=null){if(cacheKey){const remembered=await usableMeta(localStorage.getItem(cacheKey),name,'application/vnd.google-apps.folder');if(remembered)return remembered}const parentQ=parentId?` and '${escQ(parentId)}' in parents`:'';const files=await listFiles(`name='${escQ(name)}' and mimeType='application/vnd.google-apps.folder' and trashed=false${parentQ}`);const folder=files[0]||await createMetadata({name,mimeType:'application/vnd.google-apps.folder',parents:parentId?[parentId]:undefined});if(cacheKey)localStorage.setItem(cacheKey,folder.id);return folder}
async function ensureTree(){const root=await ensureFolder(ROOT_FOLDER,null,LS.folderId),active=await ensureFolder(ACTIVE_FOLDER,root.id,LS.activeFolderId),archives=await ensureFolder(ARCHIVE_FOLDER,root.id,LS.archivesFolderId),recovery=await ensureFolder(RECOVERY_FOLDER,root.id,LS.recoveryFolderId);return {root,active,archives,recovery}}
function activeName(year=currentYear()){return `Renoweet-${safeYear(year)}.json`}
async function findActive(year=currentYear()){
  year=safeYear(year);
  const tree=await ensureTree(),name=activeName(year),yearKey=LS.activeYearId+year;
  // Robust reconnect: Drive can contain duplicate Renoweet folders/files after an earlier
  // interrupted setup. Do not trust the first filename match. Collect every file this
  // OAuth app can access, validate each canonical database, and choose the highest revision.
  const ids=[];
  for(const id of [localStorage.getItem(yearKey),localStorage.getItem(LS.activeId)])if(id)ids.push(id);
  try{for(const f of await listFiles(`name='${escQ(name)}' and trashed=false`))ids.push(f.id)}catch(e){console.warn('Global active-file scan failed',e)}
  try{for(const f of await listFiles(`name='${escQ(name)}' and trashed=false and '${escQ(tree.active.id)}' in parents`))ids.push(f.id)}catch(e){console.warn('Active-folder scan failed',e)}
  const seen=new Set(),candidates=[];
  for(const id of ids){
    if(!id||seen.has(id))continue;seen.add(id);
    try{
      const meta=await usableMeta(id,name);if(!meta)continue;
      const text=await getText(id),parsed=JSON.parse(text),data=await verifyCanonical(parsed);
      if(Number(data?.meta?.year)!==Number(year))continue;
      candidates.push({meta,data,revision:Number(data?.meta?.revision||0),modified:String(meta.modifiedTime||'')});
    }catch(e){console.warn('Ignoring invalid Renoweet year candidate',id,e)}
  }
  candidates.sort((a,b)=>b.revision-a.revision||b.modified.localeCompare(a.modified));
  const best=candidates[0]?.meta||null;
  if(best){localStorage.setItem(yearKey,best.id);localStorage.setItem(LS.activeId,best.id)}
  return {tree,file:best};
}
function blankManifest(){return {schema:'renoweet.manifest',schemaVersion:1,updatedAt:now(),activeYear:currentYear(),years:{}}}
async function loadManifest(create=true){const tree=await ensureTree();let file=await usableMeta(localStorage.getItem(LS.manifestId),MANIFEST_NAME);if(!file){const files=await listFiles(`name='${MANIFEST_NAME}' and trashed=false and '${escQ(tree.root.id)}' in parents`);file=files[0]||null}if(!file){if(!create)return null;const m=blankManifest(),f=await createTextFile(MANIFEST_NAME,tree.root.id,JSON.stringify(m,null,2));localStorage.setItem(LS.manifestId,f.id);return {data:m,file:f}}localStorage.setItem(LS.manifestId,file.id);try{const data=JSON.parse(await getText(file.id));if(data.schema!=='renoweet.manifest')throw 0;data.years=data.years||{};return {data,file}}catch(e){throw new Error('Renoweet manifest is invalid. Live data was not changed.') }}
async function saveManifest(manifest,file){manifest.updatedAt=now();const text=JSON.stringify(manifest,null,2);const f=await updateTextFile(file.id,text);const back=await getText(file.id);if(await sha256Text(back)!==await sha256Text(text))throw new Error('Manifest verification failed.');return {data:manifest,file:f}}
async function updateManifestYear(year,patch){const m=await loadManifest(true);m.data.activeYear=year;m.data.years[String(year)]={...(m.data.years[String(year)]||{}),...patch};return saveManifest(m.data,m.file)}
async function maybeRecovery(remote,force=false,reason='autosave'){const year=remote.data.meta.year,key=LS.lastRecovery+year,last=Number(localStorage.getItem(key)||0);if(!force&&Date.now()-last<RECOVERY_INTERVAL_MS)return null;const tree=await ensureTree(),stamp=new Date().toISOString().replace(/[:.]/g,'-'),name=`Renoweet-${year}-r${String(remote.data.meta.revision).padStart(6,'0')}-${stamp}.json`,sealed=await sealCanonical(remote.data),file=await createTextFile(name,tree.recovery.id,JSON.stringify(sealed,null,2));localStorage.setItem(key,String(Date.now()));const files=(await listFiles(`trashed=false and '${escQ(tree.recovery.id)}' in parents`)).filter(f=>new RegExp(`^Renoweet-${year}-r`).test(f.name)).sort((a,b)=>String(b.modifiedTime).localeCompare(String(a.modifiedTime)));for(const f of files.slice(RECOVERY_KEEP)){try{await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(f.id)}`,{method:'DELETE'})}catch(e){console.warn('Could not prune old recovery snapshot',e)}}return {...file,reason}}
async function loadYear(year=currentYear(),createIfMissing=true){year=safeYear(year);localStorage.setItem(LS.year,String(year));const {tree,file}=await findActive(year);if(!file){if(!createIfMissing)return null;const fresh=await sealCanonical(blankCanonical(year)),text=JSON.stringify(fresh,null,2),made=await createTextFile(activeName(year),tree.active.id,text);localStorage.setItem(LS.activeId,made.id);localStorage.setItem(LS.activeYearId+year,made.id);await cachePut('year:'+year,fresh);await updateManifestYear(year,{activeFileId:made.id,currentRevision:0,checksum:fresh.integrity.checksum,updatedAt:fresh.meta.updatedAt});return {data:fresh,file:made,checksum:fresh.integrity.checksum}}const text=await getText(file.id);let parsed;try{parsed=JSON.parse(text)}catch(e){throw new Error('The Renoweet JSON file on Drive is not valid JSON. Nothing was overwritten. Restore a Recovery snapshot or local safety copy.')}const data=await verifyCanonical(parsed);localStorage.setItem(LS.activeId,file.id);localStorage.setItem(LS.activeYearId+year,file.id);await cachePut('year:'+year,data);return {data,file,checksum:data.integrity.checksum||await sha256Text(text)}}
function closedQuarterSet(data){const s=new Set();for(const [k,v] of Object.entries(data.periods||{}))if(v?.status==='closed')s.add(k);return s}
function diffEvents(oldArr,newArr,type){const oldMap=new Map((oldArr||[]).map(r=>[r._rid||businessKey(r,type),r])),newMap=new Map((newArr||[]).map(r=>[r._rid||businessKey(r,type),r])),events=[];for(const [id,nr] of newMap){const or=oldMap.get(id);if(!or)events.push({action:'created',id,record:nr});else if(JSON.stringify(or)!==JSON.stringify(nr))events.push({action:'updated',id,before:or,record:nr})}for(const [id,or] of oldMap)if(!newMap.has(id))events.push({action:'deleted',id,before:or});return events}
function enforceClosedPeriods(data,section,payload){const closed=closedQuarterSet(data);if(!closed.size)return;const checks=[];if(section==='bookkeeping')for(const [k,type] of [['invoices','invoice'],['expenses','expense'],['fuel','fuel'],['auto','auto']])checks.push(...diffEvents(data.bookkeeping[k],payload[k],type).map(e=>({...e,collection:k})));if(section==='os')checks.push(...diffEvents(data.os.bookkeeping,payload.bookkeeping,'invoice').map(e=>({...e,collection:'os.bookkeeping'})));for(const e of checks){const r=e.record||e.before,q=recordDate(r);if(q&&closed.has(`${q.year}-Q${q.quarter}`)){const err=new Error(`${q.year}-Q${q.quarter} is closed. This financial record cannot be changed unless the quarter is explicitly reopened.`);err.name='RenoweetClosedPeriodError';throw err}}}
function appendAudit(data,events,section){for(const e of events){const r=e.record||e.before,q=recordDate(r);data.audit.push({eventId:randId('aud'),at:now(),type:`${section}.${e.collection||'data'}.${e.action}`,recordId:e.id||'',period:q?`${q.year}-Q${q.quarter}`:'',deviceId:deviceId()})}if(data.audit.length>2000)data.audit=data.audit.slice(-2000)}
async function saveSection(section,payload,state={}){if(!['os','bookkeeping'].includes(section))throw new Error('Unknown Renoweet data section.');const year=safeYear(state.year||currentYear()),remote=await loadYear(year,true),data=remote.data,sectionKey=section==='os'?'osRevision':'bookkeepingRevision',remoteSectionRev=Number(data.meta.sections[sectionKey])||0,expected=Number(state.sectionRevision);if(Number.isFinite(expected)&&expected>=0&&remoteSectionRev!==expected){const err=new Error(`${section} changed on another device. Refresh/merge before saving.`);err.name='RenoweetConflictError';err.remote=remote;err.remoteSectionRevision=remoteSectionRev;throw err}
 const p=clone(payload);if(section==='bookkeeping')for(const [k,type,prefix] of [['invoices','invoice','inv'],['expenses','expense','exp'],['fuel','fuel','fuel'],['auto','auto','auto'],['deleted','rec','del']])inheritIds(p[k],data.bookkeeping[k],type,prefix);if(section==='os'){ensureProjectIds(p.projects);inheritIds(p.bookkeeping,data.os.bookkeeping,'invoice','osi');for(const r of p.deleted||[])if(!r._rid)r._rid=randId('del')}
 enforceClosedPeriods(data,section,p);let events=[];if(section==='bookkeeping')for(const [k,type] of [['invoices','invoice'],['expenses','expense'],['fuel','fuel'],['auto','auto'],['deleted','rec']])events.push(...diffEvents(data.bookkeeping[k],p[k],type).map(e=>({...e,collection:k})));else{events=diffEvents(data.os.bookkeeping,p.bookkeeping,'invoice').map(e=>({...e,collection:'bookkeeping'}));events.push(...diffEvents(data.os.deleted,p.deleted,'deleted-project').map(e=>({...e,collection:'os.deleted'})));events.push(...diffEvents(data.os.projects,p.projects,'project').filter(e=>e.action==='create'||e.action==='delete').map(e=>({...e,collection:'os.projects'})));}
 await maybeRecovery(remote,!!state.forceRecovery,state.recoveryReason||'save');data[section]=p;data.meta.sections[sectionKey]=remoteSectionRev+1;data.meta.revision=(Number(data.meta.revision)||0)+1;data.meta.updatedAt=now();data.meta.lastUpdatedBy=deviceId();appendAudit(data,events,section);data.audit.push({eventId:randId('aud'),at:data.meta.updatedAt,type:'save',section,revision:data.meta.revision,sectionRevision:data.meta.sections[sectionKey],deviceId:deviceId()});const sealed=await sealCanonical(data),text=JSON.stringify(sealed,null,2),updated=await updateTextFile(remote.file.id,text),verifyText=await getText(remote.file.id),verifyParsed=await verifyCanonical(JSON.parse(verifyText));if(verifyParsed.integrity.checksum!==sealed.integrity.checksum)throw new Error('Drive save verification failed. Local copy was kept and the save was not marked complete.');await cachePut('year:'+year,sealed);await updateManifestYear(year,{activeFileId:remote.file.id,currentRevision:sealed.meta.revision,checksum:sealed.integrity.checksum,updatedAt:sealed.meta.updatedAt});return {data:sealed,file:updated,checksum:sealed.integrity.checksum,sectionRevision:sealed.meta.sections[sectionKey]}}
async function updatePeriodInfo(year,quarter,patch={}){year=safeYear(year);quarter=Number(quarter);if(![1,2,3,4].includes(quarter))throw new Error('Quarter must be 1-4.');const remote=await loadYear(year,true),key=`${year}-Q${quarter}`,p=remote.data.periods[key]||{status:'open'};for(const k of ['btwStatus','filedDate','actualAmount','note'])if(Object.prototype.hasOwnProperty.call(patch,k))p[k]=patch[k];remote.data.periods[key]=p;remote.data.meta.revision++;remote.data.meta.updatedAt=now();remote.data.meta.lastUpdatedBy=deviceId();remote.data.audit.push({eventId:randId('aud'),at:remote.data.meta.updatedAt,type:'period-info',period:key,deviceId:deviceId()});const sealed=await sealCanonical(remote.data);await updateTextFile(remote.file.id,JSON.stringify(sealed,null,2));await cachePut('year:'+year,sealed);await updateManifestYear(year,{activeFileId:remote.file.id,currentRevision:sealed.meta.revision,checksum:sealed.integrity.checksum,updatedAt:sealed.meta.updatedAt});return sealed}
async function reopenQuarter(year,quarter,reason='manual reopen'){year=safeYear(year);const remote=await loadYear(year,true),key=`${year}-Q${quarter}`,p=remote.data.periods[key];if(!p)throw new Error('Unknown quarter.');await maybeRecovery(remote,true,'quarter-reopen');p.status='open';p.reopenedAt=now();p.reopenReason=reason;remote.data.meta.revision++;remote.data.meta.updatedAt=now();remote.data.audit.push({eventId:randId('aud'),at:remote.data.meta.updatedAt,type:'quarter-reopen',period:key,reason,deviceId:deviceId()});const sealed=await sealCanonical(remote.data);await updateTextFile(remote.file.id,JSON.stringify(sealed,null,2));await cachePut('year:'+year,sealed);await updateManifestYear(year,{activeFileId:remote.file.id,currentRevision:sealed.meta.revision,checksum:sealed.integrity.checksum,updatedAt:sealed.meta.updatedAt});return sealed}
async function markQuarterClosed(year,quarter,archive={}){year=safeYear(year);quarter=Number(quarter);if(![1,2,3,4].includes(quarter))throw new Error('Quarter must be 1-4.');const remote=await loadYear(year,true),data=remote.data,key=`${year}-Q${quarter}`;if(data.periods[key]?.status==='closed')throw new Error(`${key} is already closed.`);await maybeRecovery(remote,true,'quarter-close');data.periods[key]={status:'closed',closedAt:now(),archiveFileId:archive.id||null,archiveChecksum:archive.checksum||archive.md5Checksum||null,closedRevision:data.meta.revision};data.meta.revision++;data.meta.updatedAt=now();data.audit.push({eventId:randId('aud'),at:data.meta.updatedAt,type:'quarter-close',period:key,archiveFileId:archive.id||'',deviceId:deviceId()});const sealed=await sealCanonical(data);await updateTextFile(remote.file.id,JSON.stringify(sealed,null,2));await cachePut('year:'+year,sealed);const m=await loadManifest(true),entry=m.data.years[String(year)]||{};entry.activeFileId=remote.file.id;entry.currentRevision=sealed.meta.revision;entry.checksum=sealed.integrity.checksum;entry.updatedAt=sealed.meta.updatedAt;entry.quarters=entry.quarters||{};entry.quarters[`Q${quarter}`]={xlsxId:archive.id||null,name:archive.name||`Renoweet-${year}-Q${quarter}.xlsx`,checksum:archive.checksum||archive.md5Checksum||null,closedAt:sealed.meta.updatedAt};m.data.years[String(year)]=entry;m.data.activeYear=year;await saveManifest(m.data,m.file);return sealed}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
async function downloadJSON(data,name){const sealed=await sealCanonical(data);downloadBlob(new Blob([JSON.stringify(sealed,null,2)],{type:'application/json'}),name||activeName(sealed.meta.year))}
function rowsWithSource(rows,source){return (rows||[]).map(r=>({...clone(r),'Source File':r?.['Source File']||source}))}
function flattenProjects(data,source){const projects=[],customers=[],estimateItems=[],materials=[],documents=[],payments=[],orders=[],activity=[],followups=[],checklist=[];const cm=new Map();for(const p of data.os?.projects||[]){const c=p.customer||{},cid=c.id||'';if(cid&&!cm.has(cid)){const row={'Customer ID':cid,Name:c.name||'',Phone:c.phone||'',Email:c.email||'',Address:c.address||'','Source File':source};cm.set(cid,row);customers.push(row)}projects.push({'Project ID':p.id||'','Customer ID':cid,Created:p.created||'',Updated:p.updated||'',Stage:p.stage||'',Title:p.title||'',Description:p.description||'',Scope:p.scope||'',Notes:p.notes||'','Schedule Start':p.schedule?.start||'','Schedule End':p.schedule?.end||'','Schedule Time':p.schedule?.time||'','Quote Number':p.quote?.number||'','Quote Date':p.quote?.date||'','Quote Status':p.quote?.status||'','Invoice Number':p.invoice?.number||'','Invoice Date':p.invoice?.date||'','Invoice Status':p.invoice?.status||'','Acceptance Status':p.acceptance?.status||'','Acceptance Date':p.acceptance?.date||'','Source File':source});for(const x of p.estimate||[])estimateItems.push({'Project ID':p.id,'Line ID':x.id||'',Description:x.desc||'',Qty:+x.qty||0,Unit:x.unit||'',Rate:+x.rate||0,'Source File':source});for(const x of p.materials||[])materials.push({'Project ID':p.id,'Line ID':x.id||'',Material:x.desc||'',Qty:x.qty||'',Supplier:x.supplier||'',Cost:+x.cost||0,'Source File':source});for(const x of p.documents||[])documents.push({'Project ID':p.id,'Item ID':x.id||'',Date:x.date||'',Type:x.type||'',Title:x.title||'',URL:x.url||'',Notes:x.notes||'','Source File':source});for(const x of p.payments||[])payments.push({'Project ID':p.id,'Payment ID':x.id||'',Date:x.date||'',Type:x.type||'',Amount:+x.amount||0,Method:x.method||'',Status:x.status||'',Reference:x.reference||'',Notes:x.notes||'','Source File':source});for(const x of p.purchaseOrders||[])orders.push({'Project ID':p.id,'Order ID':x.id||'',Supplier:x.supplier||'',Description:x.description||'','Order Date':x.orderDate||'','Expected Date':x.expectedDate||'',Status:x.status||'',Amount:+x.amount||0,Reference:x.reference||'','Source File':source});for(const x of p.activity||[])activity.push({'Project ID':p.id,'Activity ID':x.id||'',Timestamp:x.timestamp||'',Type:x.type||'',Text:x.text||'','Source File':source});for(const x of p.followUps||[])followups.push({'Project ID':p.id,'Follow-up ID':x.id||'',Date:x.date||'',Type:x.type||'',Text:x.text||'',Done:!!x.done,'Source File':source});for(const x of p.checklist||[])checklist.push({'Project ID':p.id,'Item ID':x.id||'','Item Order':x.order||'',Item:x.text||'',Done:!!x.done,'Source File':source})}return {projects,customers,estimateItems,materials,documents,payments,orders,activity,followups,checklist}}
async function canonicalToWorkbook(data){if(typeof XLSX==='undefined')throw new Error('XLSX library is not loaded.');data=await sealCanonical(data);const y=data.meta.year,source=`Renoweet-${y}-FINAL.xlsx`,wb=XLSX.utils.book_new(),add=(name,rows)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows&&rows.length?rows:[{}]),name),f=flattenProjects(data,source);const inv=data.bookkeeping.invoices||[],exp=data.bookkeeping.expenses||[],sum=(a,k)=>(a||[]).reduce((s,r)=>s+(Number(r?.[k])||0),0);add('Summary',[{Year:y,Revision:data.meta.revision,'Paid/recorded invoices':inv.length,Expenses:exp.length,'Invoice gross':sum(inv,'Gross incl. VAT')||sum(inv,'Total incl VAT'),'Expense gross':sum(exp,'Gross'),'Closed periods':Object.entries(data.periods).filter(([,v])=>v.status==='closed').map(([k])=>k).join(', '),Checksum:data.integrity.checksum}]);add('Customers',f.customers);add('Projects',f.projects);add('Estimate Items',f.estimateItems);add('Materials',f.materials);add('Documents',f.documents);add('Payments',f.payments);add('Purchase Orders',f.orders);add('Activity',f.activity);add('FollowUps',f.followups);add('Checklist',f.checklist);add('Invoices',rowsWithSource(inv,source));add('Expenses',rowsWithSource(exp,source));add('Fuel',rowsWithSource(data.bookkeeping.fuel,source));add('Auto',rowsWithSource(data.bookkeeping.auto,source));add('Bookkeeping',rowsWithSource(data.os.bookkeeping,source));add('Deleted',[...rowsWithSource(data.os.deleted,source),...rowsWithSource(data.bookkeeping.deleted,source)]);add('Bookkeeping Control',Object.entries(data.bookkeeping.control||{}).map(([Key,Value])=>({Key,Value})));add('Periods',Object.entries(data.periods||{}).map(([Period,v])=>({Period,...v})));add('Audit',(data.audit||[]).map(r=>clone(r)));add('Archive Metadata',[{Schema:data.schema,'Schema version':data.schemaVersion,'App version':data.meta.appVersion,Year:y,'Created at':data.meta.createdAt,'Updated at':data.meta.updatedAt,Revision:data.meta.revision,'Record count':data.integrity.recordCount,'SHA-256':data.integrity.checksum}]);const json=JSON.stringify(data),chunks=[];for(let i=0;i<json.length;i+=30000)chunks.push({Part:chunks.length+1,JSON:json.slice(i,i+30000)});add('Canonical JSON',chunks);return wb}
async function downloadXLSX(data,name){const wb=await canonicalToWorkbook(data),y=normalizeCanonical(data).meta.year;XLSX.writeFile(wb,name||`Renoweet-${y}-FINAL.xlsx`)}
async function createArchiveOnDrive(data,label){if(typeof XLSX==='undefined')throw new Error('XLSX library is not loaded.');data=await sealCanonical(data);const tree=await ensureTree(),wb=await canonicalToWorkbook(data),bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'}),name=label||`Renoweet-${data.meta.year}-FINAL.xlsx`,mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',f=await createBinaryFile(name,tree.archives.id,bytes,mime);return {...f,checksum:f.md5Checksum||null}}
async function createJsonArchiveOnDrive(data,name){data=await sealCanonical(data);const tree=await ensureTree(),text=JSON.stringify(data,null,2),f=await createTextFile(name||`Renoweet-${data.meta.year}-FINAL.json`,tree.archives.id,text,'application/json');return {...f,checksum:data.integrity.checksum}}
async function createFinalArchives(year=currentYear()){const live=await loadYear(year,true);await maybeRecovery(live,true,'year-final');const xlsx=await createArchiveOnDrive(live.data,`Renoweet-${year}-FINAL.xlsx`),json=await createJsonArchiveOnDrive(live.data,`Renoweet-${year}-FINAL.json`);const m=await loadManifest(true),entry=m.data.years[String(year)]||{};entry.final={xlsxId:xlsx.id,jsonId:json.id,xlsxName:xlsx.name,jsonName:json.name,checksum:live.data.integrity.checksum,createdAt:now()};entry.activeFileId=live.file.id;entry.currentRevision=live.data.meta.revision;entry.checksum=live.data.integrity.checksum;entry.updatedAt=live.data.meta.updatedAt;m.data.years[String(year)]=entry;await saveManifest(m.data,m.file);return {xlsx,json}}
async function listArchives(){const tree=await ensureTree();return listFiles(`trashed=false and '${escQ(tree.archives.id)}' in parents`)}
async function listRecovery(year=currentYear()){const tree=await ensureTree();return (await listFiles(`trashed=false and '${escQ(tree.recovery.id)}' in parents`)).filter(f=>new RegExp(`^Renoweet-${safeYear(year)}-r`).test(f.name)).sort((a,b)=>String(b.modifiedTime).localeCompare(String(a.modifiedTime)))}
async function readDriveJsonById(id){return verifyCanonical(JSON.parse(await getText(id)))}
async function downloadCompleteBackup(year=currentYear()){if(typeof JSZip==='undefined')throw new Error('ZIP library is not loaded. Open the page while online once, then try again.');const live=await loadYear(year,true),sealed=await sealCanonical(live.data),wb=await canonicalToWorkbook(sealed),xlsx=XLSX.write(wb,{bookType:'xlsx',type:'array'}),manifest=(await loadManifest(true)).data,zip=new JSZip();zip.file(`Renoweet-${year}.json`,JSON.stringify(sealed,null,2));zip.file(`Renoweet-${year}.xlsx`,xlsx);zip.file(MANIFEST_NAME,JSON.stringify(manifest,null,2));zip.file('README.txt',`Renoweet complete offline backup\nCreated: ${now()}\nYear: ${year}\nRevision: ${sealed.meta.revision}\nSHA-256: ${sealed.integrity.checksum}\n\nThe JSON file is the exact machine-restorable source. The XLSX file is a human-readable and reconstructable archive.`);const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});downloadBlob(blob,`Renoweet-Backup-${year}-${new Date().toISOString().slice(0,10)}.zip`)}

async function listAvailableYears(){
  const years=new Set([currentYear()]);
  let activeYear=currentYear();
  try{
    const m=await loadManifest(false);
    if(m?.data){
      activeYear=Math.max(currentYear(),safeYear(m.data.activeYear||activeYear));
      for(const y of Object.keys(m.data.years||{}))if(/^\d{4}$/.test(y))years.add(Number(y));
    }
  }catch(e){console.warn('Could not read manifest years',e)}
  try{
    const files=await listFiles("name contains 'Renoweet-' and trashed=false");
    for(const f of files){const m=String(f.name||'').match(/^Renoweet-(\d{4})\.json$/);if(m)years.add(Number(m[1]))}
  }catch(e){console.warn('Could not scan yearly Renoweet files',e)}
  return {activeYear,years:[...years].filter(y=>Number.isInteger(y)&&y>=2000&&y<=2100).sort((a,b)=>b-a)};
}
async function loadExistingYear(year){return loadYear(year,false)}

function configure(){const existing=clientId(),id=prompt('Google OAuth Web Client ID\n\nCreate this once in Google Cloud Console. It is not a secret and may be stored in this browser.',existing);if(id!==null)setClientId(id);return clientId()}function getCachedYear(year=currentYear()){return cacheGet('year:'+safeYear(year))}
Object.assign(Core,{SCHEMA_VERSION,APP_VERSION,DEFAULT_GOOGLE_CLIENT_ID,DRIVE_SCOPE,blankCanonical,normalizeCanonical,verifyCanonical,sealCanonical,sha256Text,computeChecksum,countRecords,deviceId,clientId,setClientId,configure,authorize,ensureTree,loadYear,loadExistingYear,listAvailableYears,saveSection,markQuarterClosed,reopenQuarter,updatePeriodInfo,downloadJSON,downloadXLSX,canonicalToWorkbook,createArchiveOnDrive,createJsonArchiveOnDrive,createFinalArchives,downloadCompleteBackup,loadManifest,listArchives,listRecovery,readDriveJsonById,getBytes,getCachedYear,currentYear,activeName,clone,quarterFromDate});window.RenoweetDrive=Core;
})();
